<template>
  <RouterView />
</template>

<script setup>
import Head1 from '@/components/avatarParts/head/Head_1.vue'
import Top1 from '@/components/avatarParts/top/Top_1.vue'
import Top2 from '@/components/avatarParts/top/Top_2.vue'
import Top3 from '@/components/avatarParts/top/Top_3.vue'
import Top4 from '@/components/avatarParts/top/Top_4.vue'
import Top5 from '@/components/avatarParts/top/Top_5.vue'
import Top6 from '@/components/avatarParts/top/Top_6.vue'
import Top7 from '@/components/avatarParts/top/Top_7.vue'
import Top8 from '@/components/avatarParts/top/Top_8.vue'
import Top9 from '@/components/avatarParts/top/Top_9.vue'
import Top10 from '@/components/avatarParts/top/Top_10.vue'
import Top11 from '@/components/avatarParts/top/Top_11.vue'
import Mouth1 from '@/components/avatarParts/mouth/Mouth_1.vue'
import Mouth2 from '@/components/avatarParts/mouth/Mouth_2.vue'
import Mouth3 from '@/components/avatarParts/mouth/Mouth_3.vue'
import Mouth4 from '@/components/avatarParts/mouth/Mouth_4.vue'
import Mouth5 from '@/components/avatarParts/mouth/Mouth_5.vue'
import Mouth6 from '@/components/avatarParts/mouth/Mouth_6.vue'
import Mouth7 from '@/components/avatarParts/mouth/Mouth_7.vue'
import Glasses1 from '@/components/avatarParts/glasses/Glasses_1.vue'
import Glasses2 from '@/components/avatarParts/glasses/Glasses_2.vue'
import Glasses3 from '@/components/avatarParts/glasses/Glasses_3.vue'
import Eyes1 from '@/components/avatarParts/eyes/Eyes_1.vue'
import Eyes2 from '@/components/avatarParts/eyes/Eyes_2.vue'
import Eyes3 from '@/components/avatarParts/eyes/Eyes_3.vue'
import Eyes4 from '@/components/avatarParts/eyes/Eyes_4.vue'
import Eyes5 from '@/components/avatarParts/eyes/Eyes_5.vue'
import Eyebrows1 from '@/components/avatarParts/eyebrows/Eyebrows_1.vue'
import Eyebrows2 from '@/components/avatarParts/eyebrows/Eyebrows_2.vue'
import Eyebrows3 from '@/components/avatarParts/eyebrows/Eyebrows_3.vue'
import Eyebrows4 from '@/components/avatarParts/eyebrows/Eyebrows_4.vue'
import Eyebrows5 from '@/components/avatarParts/eyebrows/Eyebrows_5.vue'
import Eyebrows6 from '@/components/avatarParts/eyebrows/Eyebrows_6.vue'
import Body1 from '@/components/avatarParts/body/Body_1.vue'
import Body2 from '@/components/avatarParts/body/Body_2.vue'
import Body3 from '@/components/avatarParts/body/Body_3.vue'
import Body4 from '@/components/avatarParts/body/Body_4.vue'
import Body5 from '@/components/avatarParts/body/Body_5.vue'
import Body6 from '@/components/avatarParts/body/Body_6.vue'
import Background1 from '@/components/avatarParts/background/Background_1.vue'
import Background2 from '@/components/avatarParts/background/Background_2.vue'
import Background3 from '@/components/avatarParts/background/Background_3.vue'
import Background4 from '@/components/avatarParts/background/Background_4.vue'
import Background5 from '@/components/avatarParts/background/Background_5.vue'
import Pet1 from '@/components/avatarParts/pet/Pet_1.vue'
import Pet2 from '@/components/avatarParts/pet/Pet_2.vue'
import Pet3 from '@/components/avatarParts/pet/Pet_3.vue'
import Pet4 from '@/components/avatarParts/pet/Pet_4.vue'
</script>